/*
 * 4th Year Project
 *
 * (Will come up with a better name later)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CharacterListInner : IEquatable<CharacterListInner>
    { 
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [Required]
        [DataMember(Name="name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Height
        /// </summary>
        [DataMember(Name="height")]
        public int? Height { get; set; }

        /// <summary>
        /// Gets or Sets Mass
        /// </summary>
        [DataMember(Name="mass")]
        public decimal? Mass { get; set; }

        /// <summary>
        /// Gets or Sets HairColor
        /// </summary>
        [DataMember(Name="hair_color")]
        public string HairColor { get; set; }

        /// <summary>
        /// Gets or Sets SkinColor
        /// </summary>
        [DataMember(Name="skin_color")]
        public string SkinColor { get; set; }

        /// <summary>
        /// Gets or Sets EyeColor
        /// </summary>
        [DataMember(Name="eye_color")]
        public string EyeColor { get; set; }

        /// <summary>
        /// Gets or Sets BirthYear
        /// </summary>
        [DataMember(Name="birth_year")]
        public string BirthYear { get; set; }

        /// <summary>
        /// Gets or Sets Gender
        /// </summary>
        [DataMember(Name="gender")]
        public string Gender { get; set; }

        /// <summary>
        /// Gets or Sets Homeworld
        /// </summary>
        [DataMember(Name="homeworld")]
        public string Homeworld { get; set; }

        /// <summary>
        /// Gets or Sets Species
        /// </summary>
        [DataMember(Name="species")]
        public string Species { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CharacterListInner {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("  Mass: ").Append(Mass).Append("\n");
            sb.Append("  HairColor: ").Append(HairColor).Append("\n");
            sb.Append("  SkinColor: ").Append(SkinColor).Append("\n");
            sb.Append("  EyeColor: ").Append(EyeColor).Append("\n");
            sb.Append("  BirthYear: ").Append(BirthYear).Append("\n");
            sb.Append("  Gender: ").Append(Gender).Append("\n");
            sb.Append("  Homeworld: ").Append(Homeworld).Append("\n");
            sb.Append("  Species: ").Append(Species).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CharacterListInner)obj);
        }

        /// <summary>
        /// Returns true if CharacterListInner instances are equal
        /// </summary>
        /// <param name="other">Instance of CharacterListInner to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CharacterListInner other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    Height == other.Height ||
                    Height != null &&
                    Height.Equals(other.Height)
                ) && 
                (
                    Mass == other.Mass ||
                    Mass != null &&
                    Mass.Equals(other.Mass)
                ) && 
                (
                    HairColor == other.HairColor ||
                    HairColor != null &&
                    HairColor.Equals(other.HairColor)
                ) && 
                (
                    SkinColor == other.SkinColor ||
                    SkinColor != null &&
                    SkinColor.Equals(other.SkinColor)
                ) && 
                (
                    EyeColor == other.EyeColor ||
                    EyeColor != null &&
                    EyeColor.Equals(other.EyeColor)
                ) && 
                (
                    BirthYear == other.BirthYear ||
                    BirthYear != null &&
                    BirthYear.Equals(other.BirthYear)
                ) && 
                (
                    Gender == other.Gender ||
                    Gender != null &&
                    Gender.Equals(other.Gender)
                ) && 
                (
                    Homeworld == other.Homeworld ||
                    Homeworld != null &&
                    Homeworld.Equals(other.Homeworld)
                ) && 
                (
                    Species == other.Species ||
                    Species != null &&
                    Species.Equals(other.Species)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    if (Height != null)
                    hashCode = hashCode * 59 + Height.GetHashCode();
                    if (Mass != null)
                    hashCode = hashCode * 59 + Mass.GetHashCode();
                    if (HairColor != null)
                    hashCode = hashCode * 59 + HairColor.GetHashCode();
                    if (SkinColor != null)
                    hashCode = hashCode * 59 + SkinColor.GetHashCode();
                    if (EyeColor != null)
                    hashCode = hashCode * 59 + EyeColor.GetHashCode();
                    if (BirthYear != null)
                    hashCode = hashCode * 59 + BirthYear.GetHashCode();
                    if (Gender != null)
                    hashCode = hashCode * 59 + Gender.GetHashCode();
                    if (Homeworld != null)
                    hashCode = hashCode * 59 + Homeworld.GetHashCode();
                    if (Species != null)
                    hashCode = hashCode * 59 + Species.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CharacterListInner left, CharacterListInner right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CharacterListInner left, CharacterListInner right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
