version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=starwars
      - DB_PWD=starwars
    ports:
      - 8080:8080
  
  db:
    image: ghcr.io/linuxserver/mariadb
    expose:
      - 3306
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=helloworld
      - TZ=Europe/London
      - MYSQL_DATABASE=starwars
      - MYSQL_USER=starwars
      - MYSQL_PASSWORD=starwars
    volumes:
      - /home/bubsy/docker/db:/config

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=helloworld

  revproxy:
    image: nginx
    depends_on:
      - api
    ports:
      - 80:80
    volumes:
      - ./api.conf:/etc/nginx/conf.d/default.conf
